### ISSUE TITLE
Solution : ImportError: bad magic number in 'notebook_grader': b'3\r\r\n'

### ISSUE THREAD

**Issue by qiaoxu123** [qiaoxu123/Self-Driving-Cars#1]
If you are getting the following error
`from notebook_grader import BicycleSolution, grade_bicycle
ImportError: bad magic number in 'notebook_grader': b'3\r\r\n'`

I hope Coursera Will help us and find a better solution

Solution Here

Download the following

https://github.com/MShokry/BikeSelfDrive/blob/master/grading.py

`The De-Compiled Version of Grading`

and upload to the environment and change the first line to

from grading import BicycleSolution, grade_bicycle

It will work like a charm :)

**Comment by qiaoxu123** [comment]
Any question ,please check the Coursera forum firstly, like this 
https://www.coursera.org/learn/intro-self-driving-cars/discussions/weeks/4/threads/rQeClmjEEemX9Q5TqxEL0g

**Comment by uscgongjianxin** [comment]
Thanks so much, this solution solves my problem.

**Comment by OsamaElsisi** [comment]
Hi,
i want the figure8.txt of that solution please
and the xdata.txt for Longitudinal_Vehicle_Model
before 4/8/2019  please send to me thanks
https://github.com/OsamaElsisi

**Comment by OsamaElsisi** [comment]
for submitt please
