### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by xiafeng5127** [qiaoxu123/Self-Driving-Cars#5]
您好，一直尝试在github下载这些资料，但是一直失败，有可能把这个资料分享网盘吗，麻烦了，多谢

**Comment by lntsh854** [comment]
一样的问题，请问作者能分享吗？

**Comment by qiaoxu123** [comment]
你好，我重新push到coding上了，可以去这clone。
[链接](https://qiaoxu.coding.net/p/Self-Driving-Cars)

**Comment by qiaoxu123** [comment]
某度盘有文件限制。。

**Comment by EthanCodesss** [comment]
点进coding 需要登陆团队 怎么解决呀
